version: "3.8"
services: 
  sonarqube:
    container_name: sonarqube_server
    image: sonarqube:community
    networks:
      sonarqube:
        aliases:
          - sonarqube
    volumes:
      - ./conf:/opt/sonarqube/conf
      - ./data:/opt/sonarqube/data
      - ./logs:/opt/sonarqube/logs
      - ./extensions:/opt/sonarqube/extensions
    ports:
      - 9000:9000
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"
      SONAR_JDBC_URL: jdbc:postgresql://postgresql:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: ZTdiNzhhODMwMjk0ZDM1ODAwYjg3OWM3
  
  postgres:
    container_name: sonarqube_postgres
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: ZTdiNzhhODMwMjk0ZDM1ODAwYjg3OWM3
    volumes:
      - sonarqube_postgres:/var/lib/postgresql/data
    expose:
      - 5432
    networks: 
      sonarqube:
        aliases: 
          - postgresql
  
  nginx:
    container_name: sonarqube_nginx
    image: nginx:stable
    volumes:
      - ./certs:/app/:ro
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
    networks:
      sonarqube:
        aliases:
          - nginx
    ports:
      - 80:80
      - 443:443

volumes:
  sonarqube_postgres:

networks:
  sonarqube:
    driver: bridge
    